---
title: "Project Proposal: Maternal & Reproductive Health in NYC"
author: "Ayeshra Acharya (aa4478), Zaynub Ibrahim (zi2125), Cynthia Liu (cl3938), Shelley Shen (ss5932)"
output: github_document
---

### Motivation

Recent events in American politics - a surging pro-life movement, an increasingly conservative Supreme Court, and pending litigation against the Affordable Care Act (ACA) will potentially restrict access to reproductive services & resources for women across the country. 

We seek to highlight the importance of such services by demonstrating how increased access to reproductive services decreases rates of STDs/STIs and maternal mortality in New York City, and how these health outcomes vary by socioeconomic factors like income and race. 

### Final Products

- Geospatial map of availability of reproductive services
- Plots comparing levels of STDs/STIs and maternal mortality with and without insurance coverage
- Scatter plot of prevalence of STDs/STIs by proximity to reproductive services 
- Histogram comparing health outcomes based on different levels of income and between different races
- Website of project description, analysis and visualizations
- Screencast of website 

### Data Sources

We plan to use a few datasets from the NYC Department of Health and Mental Hygiene to perform our analysis and data visualization. 


- We will use the NYC OpenData [Condom Availability Program dataset](https://data.cityofnewyork.us/Health/NYC-Condom-Availability-Program-HIV-condom-distrib/4kpn-sezh) to understand the availability of free safer sex products in NYC. 
- We will use the NYC OpenData [Pregnancy-Associated Mortality dataset](https://data.cityofnewyork.us/Health/Pregnancy-Associated-Mortality/27x4-cbi6) to analyze the distribution of maternal mortality and its social determinants in NYC. 
- We will use the NYC OpenData [HIV/AIDS Diagnoses by Neighborhood, Age Group, and Race/Ethnicity dataset](https://data.cityofnewyork.us/Health/HIV-AIDS-Diagnoses-by-Neighborhood-Age-Group-and-R/dxnu-p2qd) to look at how neighborhood income level and race affect HIV/AIDS diagnoses. 
- We will manually find the geographical coordinates of Planned Parenthood clinics throughout NYC using the [Planned Parenthood Health Centers in New York list](https://www.plannedparenthood.org/health-center/ny) and Google Maps. 
- We will potentially use the NYC OpenData [DOHMH Community Health Survey](https://data.cityofnewyork.us/Health/DOHMH-Community-Health-Survey-2010-2016-/csut-3wpr) to obtain the prevalence of health care insurance coverage. 

- We will also reach out to Mailman professors who conduct research in the field of reproductive services and maternal health and ask for guidance in finding more comprehensive datasets. 


### Planned Analyses / Visualizations / Coding Challenges

- We anticipate using QGIS to map access to reproductive services on a national level and how it may vary by state. 
- We will run regression models to look at how socioeconomic factors such as income and race and access to reproductive services impact maternal mortality and STD/STI rates. 
- Since we are analyzing multiple datasets, a possible coding challenge is identifying the relevant variables of interest and determining how to manipulate the datasets. 
- Another anticipated challenge is how to merge the datasets in order to perform our regression analysis


### Planned Timeline 
- November 13th: Literature review and finalize variables of interest in project review meeting
- November 175h: Meet with Data Science I TA to go over project plan and address challenges
- November 20th: Read in and tidy datasets, assign plot creations 
- November 27th: Project analysis, visualizations, and discussion of results
- November 30th: Finalize written report with project details
- December 4th: Finalize project report, webpage, and screencast  




